-- Enable the pgvector extension to work with embedding vectors (optional, for future AI search)
-- create extension vector;

-- Create table for papers
create table if not exists papers (
  id bigint generated by default as identity primary key,
  category_slug text not null, -- e.g. 'cs_CV', 'cs_AI'
  title text not null,
  published_date date not null,
  authors text,
  institution text,
  link text,
  code_url text,
  thumbnail_url text,
  summary text,
  contributions text,
  mindmap text,
  tags text[], -- Array of strings
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Constraint to prevent duplicate papers (assuming link is unique)
  constraint papers_link_key unique (link)
);

-- Set up Row Level Security (RLS)
-- 1. Enable RLS
alter table papers enable row level security;

-- 2. Create Policy for Public Read Access
create policy "Public papers are viewable by everyone"
  on papers for select
  using ( true );

-- 3. Create Policy for Service Role (Write Access)
-- Usually service role bypasses RLS, but explicit policy helps avoid 42501
create policy "Service role can do everything"
  on papers for all
  using ( true )
  with check ( true );


-- Create indexes for common query patterns
create index if not exists papers_category_date_idx on papers (category_slug, published_date desc);
create index if not exists papers_published_date_idx on papers (published_date desc);
